common: &common
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  username: postgres
  password:
  reconnect: true
  pool: 5

development:
  <<: *common
  database: rbdc_development

test: &test
  <<: *common
  database: rbdc_test

production:
  <<: *common
  database: rbdc_production
